export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const GET_EMPLOYEE = "GET_EMPLOYEE";

export const ADD_LEAVE = "ADD_LEAVE";
export const GET_LEAVES = "GET_LEAVES";
export const DELETE_LEAVE = "DELETE_LEAVE";